### ISSUE TITLE
gstreamer receives http 410

### ISSUE THREAD

**Issue by cskollar** [vitiko98/mopidy-qobuz#7]
After some inactivity (a few hours), some Qobuz tracks cannot be played in Mopidy. In the debug log I see the following (the url is anonymized):

`[MainThread] mopidy.audio.gst Got ERROR bus message: error=GLib.Error('Gone', 'gst-resource-error-quark', 5) debug='../ext/soup/gstsouphttpsrc.c(1690): gst_soup_http_src_parse_status (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin5/GstSoupHTTPSrc:source:\nGone (410), URL: https://streaming-qobuz-std.akamaized.net/file?uid=********&eid=********&fmt=7&profile=raw&app_id=*********&cid=*******&etsp=**********&hmac=***************************, Redirect to: (NULL)'`

The issue doesn't affect every track, it's random. I've noticed that within an album, I get 410 from the Qobuz CDN for around 10% of the songs. After restarting Mopidy, the issue gets resolved.

How I tested it: I copied the URLs to another host (the faulty URL with http 410, and the working URL after the restart). When tested with curl, the faulty URL also receives a 410 error on the other host. The only difference between the two URLs is in the **etsp** and the **hmac** parameters.

**Comment by vitiko98** [comment]
IIRC this issue is solved in dev branch. You can try installing it with `pip install git+https://github.com/vitiko98/mopidy-qobuz@dev`

I didn't merge it to main yet because I don't have a Qobuz account to test (for now).
